### ISSUE TITLE
Dragging a new avatar into avatar animator does not load new avatars

### ISSUE THREAD

**Issue by dmey** [letmaik/pose-animator#24]
It appears this has not effect -- tested compiling from master.

**Comment by letmaik** [comment]
Works for me.

**Comment by dmey** [comment]
This is actually not an issue -- my confusion arose from my expectation of seeing the svg being added to the drop down menu. This is not an issue but rather a minor limitation that would prevent users from flipping through designs. I will make a note in the readme file when addressing #26.
